FROM registry.altlinux.org/alt/alt

RUN apt-get update \
    && apt-get install -y golang gcc \
    && rm -f /var/cache/apt/archives/*.rpm /var/cache/apt/*.bin /var/lib/apt/lists/*.*

WORKDIR /service
COPY . .
