GET http://localhost:9111/register?prefix=ALT-SA

###
GET http://localhost:9111/register?prefix=ALT-SA-

###
GET http://localhost:9111/register?prefix=ALT-SA-1

###
GET http://localhost:9111/register?prefix=SA

###
GET http://localhost:9111/register?prefix=""

###
GET http://localhost:9111/register?prefix=

###
POST http://localhost:9111/update?name=ALT-SA-1011-1

###
GET http://localhost:9111/update?name=ALT-SA-1011-1

###
GET http://localhost:9111/check?name=ALT-SA-1021-1
